apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: clean-folder
spec:
  arguments:
    parameters:
      - name: folderid
        value: '12345678'
      - name: hubid
        value: '12345678'
  entrypoint: template
  imagePullSecrets:
    - name: waicosnovadi
    - name: cnvwebshop
  metrics:
    prometheus: []
  onExit: exit-handler
  templates:
    - name: template
      steps:
        - - arguments:
              parameters:
                - name: folderid
                  value: '{{workflow.parameters.folderid}}'
                - name: hubid
                  value: '{{workflow.parameters.hubid}}'
            name: step1
            template: step1
    # Step 1 - Clean specified Hub
    - inputs:
        parameters:
          - name: folderid
          - name: hubid
      metrics:
        prometheus: []
      name: step1
      outputs:
        parameters: []
      script:
        args: []
        command:
          - /bin/sh
        env:
          - name: FOLDERID
            value: '{{workflow.parameters.folderid}}'
          - name: HUBID
            value: '{{workflow.parameters.hubid}}'
          - name: CLIENTID
            value: 'c81b7886-f62b-4cad-ba01-02ca63026588'
          - name: CLIENTSECRET
            valueFrom:
              secretKeyRef:
                key: CLIENTSECRET
                name: dc-cli
        image: 'cnvwebshop.azurecr.io/dc-cli:95ad01fc'
        source: |
          dc-cli configure --clientId $CLIENTID --clientSecret $CLIENTSECRET --hubId $HUBID

          dc-cli content-item archive --folderId $FOLDERID --force
    - name: exit-handler
      steps:
      - - arguments:
            parameters:
            - name: status
              value: '{{workflow.status}}'
            - name: failures
              value: '{{workflow.failures}}'
          name: notify-teams-failure
          templateRef:
            name: teams-exithandler
            template: notify-teams-failure
          when: '{{workflow.status}} != Succeeded'          
  ttlStrategy:
    secondsAfterCompletion: 600
    secondsAfterFailure: 259200
    secondsAfterSuccess: 600
