apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: dc-cli-essprod-2-esspreprod
spec:
  arguments:
    parameters:
      - name: parameters
        value: 'default-value'
  entrypoint: template
  imagePullSecrets:
    - name: waicosnovadi
    - name: cnvwebshop
  metrics:
    prometheus: []
  templates:
    - name: template
      steps:
        - - arguments:
              parameters:
                - name: parameters
                  value: '{{workflow.parameters.parameters}}'
            name: step1
            template: step1
        - - name: step2
            template: step2
        - - name: step3
            template: step3
    # Step 1 - Get dc-cli Verison
    - inputs:
        parameters:
          - name: parameters
      metrics:
        prometheus: []
      name: step1
      outputs:
        parameters: []
      script:
        args: []
        command:
          - /bin/sh
        env:
          - name: PARAMETERS
            value: '{{workflow.parameters.parameters}}'
          - name: CLIENTSECRET
            valueFrom:
              secretKeyRef:
                key: CLIENTSECRET
                name: dc-cli
        image: 'waicosnovadi.azurecr.io/dc-cli:build-pipeline'
        source: |
          dc-cli --version
    # Step 2 - Login to Amplience and Clean Hub
    - inputs:
      metrics:
        prometheus: []
      name: step2
      outputs:
        parameters: []
      script:
        args: []
        command:
          - /bin/sh
        env:
          - name: ESSPREPROD
            value: '5f1afad652faff0001983332'
          - name: CLIENTID
            value: 'c81b7886-f62b-4cad-ba01-02ca63026588'
          - name: CLIENTSECRET
            valueFrom:
              secretKeyRef:
                key: CLIENTSECRET
                name: dc-cli
        image: 'waicosnovadi.azurecr.io/dc-cli:build-pipeline'
        source: |
          dc-cli configure --clientId $CLIENTID --clientSecret $CLIENTSECRET --hubId $ESSPREPROD

          dc-cli hub clean --hubId $ESSPREPROD --force
    # Step 3 - Copy Source Hub to Destination Hub
    - inputs:
      metrics:
        prometheus: []
      name: step3
      outputs:
        parameters: []
      script:
        args: []
        command:
          - /bin/sh
        env:
          - name: ESSPREPROD
            value: '5f1afad652faff0001983332'
          - name: ESSPROD
            value: '5f1afbf752faff00018681f5'
          - name: CLIENTID
            value: 'c81b7886-f62b-4cad-ba01-02ca63026588'
          - name: CLIENTSECRET
            valueFrom:
              secretKeyRef:
                key: CLIENTSECRET
                name: dc-cli
        image: 'waicosnovadi.azurecr.io/dc-cli:build-pipeline'
        source: |
          dc-cli configure --clientId $CLIENTID --clientSecret $CLIENTSECRET --hubId $ESSPROD

          dc-cli hub clone $ESSPROD --dstHubId $ESSPREPROD --publish --force

          dc-cli hub clone $ESSPROD --dstHubId $ESSPREPROD --step content --publish --force
  ttlStrategy:
    secondsAfterCompletion: 600
    secondsAfterFailure: 259200
    secondsAfterSuccess: 600
