apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: publish-essprod
spec:
  arguments:
    parameters:
      - name: localelist
        value: 'de-DE|en-GB...'
      - name: workflowidlist
        value: '1234abc|456def|789ghi... '
  entrypoint: template
  imagePullSecrets:
    - name: waicosnovadi
    - name: cnvwebshop
  metrics:
    prometheus: []
  templates:
    - name: template
      steps:
        - - arguments:
              parameters:
                - name: localelist
                  value: '{{workflow.parameters.localelist}}'
                - name: workflowidlist
                  value: '{{workflow.parameters.workflowidlist}}'
            name: step1
            template: step1
    # Step 1 - Publish Job
    - inputs:
        parameters:
          - name: localelist
          - name: workflowidlist
      metrics:
        prometheus: []
      name: step1
      outputs:
        parameters: []
      script:
        args: []
        command:
          - /bin/sh
        env:
          - name: LOCALELIST
            value: '{{workflow.parameters.localelist}}'
          - name: WORKFLOWIDLIST
            value: '{{workflow.parameters.workflowidlist}}'
          - name: ESSPROD
            value: '5f1afbf752faff00018681f5'
          - name: CONTENTID
            value: '5f1afbfecff47e0001e5b3d0' # ESSPROD Content Repo ID
          - name: CLIENTID
            value: 'c81b7886-f62b-4cad-ba01-02ca63026588'
          - name: CLIENTSECRET
            valueFrom:
              secretKeyRef:
                key: CLIENTSECRET
                name: dc-cli
        image: 'cnvwebshop.azurecr.io/dc-cli:95ad01fc'
        source: |
          dc-cli configure --clientId $CLIENTID --clientSecret $CLIENTSECRET --hubId $ESSPROD

          dc-cli content-item publish --facet "schema:/CheckoutRetailerSelectionPage|CheckoutshoppingCartPage|ContactPage|ErrorPage|ProductDetailPage|ProductListPage|SearchResultPage|ServicePage|StorefinderPage/, locale:/$LOCALELIST/, workflowId:/$WORKFLOWIDLIST/" --repoId $CONTENTID
  ttlStrategy:
    secondsAfterCompletion: 600
    secondsAfterFailure: 259200
    secondsAfterSuccess: 600
