apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: publish-content
spec:
  arguments:
    parameters:
      - name: localelist
        value: 'de-DE|en-GB...'
      - name: hubid
        value: '1234567890'
      - name: contentid
        value: '1234567890'
  entrypoint: template
  imagePullSecrets:
    - name: waicosnovadi
    - name: cnvwebshop
  metrics:
    prometheus: []
  onExit: exit-handler
  templates:
    - name: template
      steps:
        - - arguments:
              parameters:
                - name: localelist
                  value: '{{workflow.parameters.localelist}}'
                - name: hubid
                  value: '{{workflow.parameters.hubid}}'
                - name: contentid
                  value: '{{workflow.parameters.contentid}}'
            name: step1
            template: step1
    # Step 1 - Publish Job
    - inputs:
        parameters:
          - name: localelist
          - name: hubid
          - name: contentid
      metrics:
        prometheus: []
      name: step1
      outputs:
        parameters: []
      script:
        args: []
        command:
          - /bin/sh
        env:
          - name: LOCALELIST
            value: '{{workflow.parameters.localelist}}'
          - name: HUBID
            value: '{{workflow.parameters.hubid}}'
          - name: CONTENTID
            value: '{{workflow.parameters.contentid}}'
          - name: CLIENTID
            value: 'c81b7886-f62b-4cad-ba01-02ca63026588'
          - name: CLIENTSECRET
            valueFrom:
              secretKeyRef:
                key: CLIENTSECRET
                name: dc-cli
        image: 'cnvwebshop.azurecr.io/dc-cli:build-pipeline'
        source: |
          dc-cli configure --clientId $CLIENTID --clientSecret $CLIENTSECRET --hubId $HUBID

          dc-cli content-item publish --facet "locale:/$LOCALELIST/" --repoId $CONTENTID

          echo $?
          echo "exit code"

        volumeMounts:
          - mountPath: /mnt
            name: storage
            readOnly: false
    - name: exit-handler
      steps:
        - - arguments:
              parameters:
                - name: status
                  value: '{{workflow.status}}'
                - name: failures
                  value: '{{workflow.failures}}'
            name: notify-teams-failure
            templateRef:
              name: teams-exithandler
              template: notify-teams-failure
  volumes:
    - azureFile:
        readOnly: false
        secretName: webshop1storage
        shareName: data/amplience
      name: storage
  ttlStrategy:
    secondsAfterCompletion: 600
    secondsAfterFailure: 259200
    secondsAfterSuccess: 600