apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: dc-cli
spec:
  arguments:
    parameters:
      - name: brand
        value: 'cat or ess?'
      - name: hubid
        value: '1 or 2 or 3 or 4 or 5 or 6...?'
  entrypoint: template
  imagePullSecrets:
    - name: waicosnovadi
    - name: waiwunderci
    - name: waicosnovaml
  metrics:
    prometheus: []
  templates:
    - name: template
      steps:
        - - arguments:
              parameters:
                - name: brand
                  value: '{{workflow.parameters.brand}}'
                - name: hubid
                  value: '{{workflow.parameters.hubid}}'
            name: step1
            template: step1
        - - name: step2
            template: step2
    - inputs:
        parameters:
          - name: brand
          - name: hubid
      metrics:
        prometheus: []
      name: step1
      outputs:
        parameters: []
      script:
        args: []
        command:
          - /bin/sh
        env:
          - name: Brand
            value: '{{workflow.parameters.brand}}'
          - name: HubID
            value: '{{workflow.parameters.hubid}}'
          - name: CLIENTID
            value: 'c81b7886-f62b-4cad-ba01-02ca63026588'
          - name: CATPLAY
            value: '60d9d13bc9e77c000105146d'
          - name: CLIENTSECRET
            valueFrom:
              secretKeyRef:
                key: CLIENTSECRET
                name: dc-cli
        image: 'waicosnovadi.azurecr.io/dc-cli:build-pipeline'
        source: |
          dc-cli configure --clientId $CLIENTID --clientSecret $CLIENTSECRET --hubId $hubid
          dc-cli hub clean --hubId $CATPLAY --force
    - inputs:
      metrics:
        prometheus: []
      name: step2
      outputs:
        parameters: []
      script:
        args: []
        command:
          - /bin/sh
        env:
          - name: CLIENTSECRET
            valueFrom:
              secretKeyRef:
                key: CLIENTSECRET
                name: dc-cli
        image: 'waicosnovadi.azurecr.io/dc-cli:build-pipeline'
        source: |
          dc-cli --version          
  ttlStrategy:
    secondsAfterCompletion: 600
    secondsAfterFailure: 259200
    secondsAfterSuccess: 600